full_rebuild: true
name: Microsoft Cities Unlocked
author: Ryan, Nadia and Stefan
url: http://students.cs.ucl.ac.uk/2016/group4
version: V 1.0
encoding: utf-8
defaults:
  -
    values:
      layout: "index"
markdown: kramdown
kramdown:
  input: GFM
relative_permalinks: false
collections:
- entries
sass:
  sass_dir: _sass
  style: :compressed
exclude: [
.git,
.gitignore,
README.md,
.sass-cache
]
